version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: url-shortener-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: url-shortener
    volumes:
      - mongodb_data:/data/db
    networks:
      - url-shortener-network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: url-shortener-nextjs-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/url-shortener?authSource=admin
      NODE_ENV: development
    depends_on:
      - mongodb
    networks:
      - url-shortener-network
    volumes:
      # Mount source code for hot reloading
      - ./app:/app/app
      - ./lib:/app/lib
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./next.config.ts:/app/next.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./postcss.config.mjs:/app/postcss.config.mjs
      # Exclude node_modules to use container's version
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  url-shortener-network:
    driver: bridge 